### ISSUE TITLE
IRL_adm1.shp missing extra files

### ISSUE THREAD

**Issue by jurtasunel** [SaM-92/Choropleth-map-Ireland#1]
Hello!

I really like your Chloropleth tutorial with the map of Ireland. I am trying to follow the code but I can't seem to open the file you have in your github named as "map of ireland", the IRL_adm1.shp. If I understand it correctly, the .shp needs to be in a directory with other related files to produce the map right? Can you let me know which other files you use? OR maybe they are somewhere in your github too and I missed it? Thanks a lot in advance!

Cheers,
Josemari

**Comment by SaM-92** [comment]
Hi Josemari,

Thank you for your comment. I think you missed the file. Please follow this link and you should be able to see it. 

https://github.com/SaM-92/Choropleth-map-Ireland

**Comment by jurtasunel** [comment]
Hi,

Many thanks for your quick response. I can see four files in that link, the code.py, the data.csv, the README.md and the map.shp. The map downloads one single shp file and after following the code word by word, I get an error stating "Unable to open ~path//IRL_adm1.shx Set SHAPE_RESTORE_SHX config option to YES to restore or create it". I have done a bit of reading and it looks like the shp file is missing the additional files .shx, .dbf and .prj. Can you help me out with this. Million thanks in advance!

Cheers

**Comment by SaM-92** [comment]
Hi Josemari,

I apologise for the late reply. I had no time to go through it sooner! 

The problem is that the map files were not complete enough to run the code. Thanks for spotting it! 👍 

I have uploaded a zip file now by which you should be able to run the code now. The code does not need any change, just please extract the zip file to the "path".

Cheers
SaM

**Comment by jurtasunel** [comment]
Thank you for your reply. I will give it another go when I have chance,
thanks again!

Josemari

**Comment by SaM-92** [comment]
My pleasure Josemari! :)
